### ISSUE TITLE
您好，有数据库相关的sql吗？

### ISSUE THREAD

**Issue by xionglian** [Mr-Yin-Sup/huikao#3]
项目中没有找到创建mysql数据库的sql

**Comment by Mr-Yin-Sup** [comment]
数据库脚本在根目录
&nbsp;


Young
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年9月11日(星期一) 下午2:24
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [Mr-Yin-Sup/huikao] 您好，有数据库相关的sql吗？ (Issue #3)





 
项目中没有找到创建mysql数据库的sql
