### ISSUE TITLE
前后端部署在同一台阿里云服务器，小程序部署在服务器的Nginx上面，小程序发送请求的时候报跨域的错误，百度查找了很多方法，一直没能解决，请指点一下。

### ISSUE THREAD

**Issue by iamsxy** [Mr-Yin-Sup/huikao#4]

**Comment by Mr-Yin-Sup** [comment]
贴出配置文件

**Comment by iamsxy** [comment]
![Snipaste_2023-10-25_14-03-11](https://github.com/Mr-Yin-Sup/huikao/assets/85863237/a0ce5fd6-3d67-4e42-8059-bea7f88f4e87)

**Comment by iamsxy** [comment]
![图片](https://github.com/Mr-Yin-Sup/huikao/assets/85863237/0f533dd0-2858-4e14-968f-60c8f2257538)

**Comment by iamsxy** [comment]
前端和后端只修改了基本的信息，后台可正常访问

**Comment by iamsxy** [comment]
本地可以正常运行，部署上线则报错

**Comment by Mr-Yin-Sup** [comment]
我想你应该想说的是部署h5 而不是小程序，要想解决跨域问题前端和后端应该通过nginx使用同一个端口进行代理访问，请参考以下：
![image](https://github.com/Mr-Yin-Sup/huikao/assets/53851602/c6c7e32f-9b0d-4f7c-8fbc-cae040cb241f)
根据你目前的配置，前端访问的端口应该是nginx暴露的80端口而不是服务的8881端口

**Comment by iamsxy** [comment]
我把前端的端口修改为80之后，不会显示跨域问题，但会报404的错误，资源请求不到
![图片](https://github.com/Mr-Yin-Sup/huikao/assets/85863237/87f6e8d1-a7a4-4205-82d3-58633868513f)

**Comment by Mr-Yin-Sup** [comment]
也许是nginx配置问题,请参考我的配置进行修改
